-- -- 1
-- SELECT *
-- FROM (
--     SELECT e.*
--     FROM employees e
--     ORDER BY e.emp_id
-- )
-- WHERE ROWNUM <= 3;

-- 2
-- SELECT *
-- FROM (
--     SELECT e.emp_id, e.emp_name, e.salary
--     FROM employees e
--     WHERE e.salary IS NOT NULL
--     ORDER BY e.salary DESC
-- )
-- WHERE ROWNUM <= 2;

-- 3
-- SELECT *
-- FROM (
--     SELECT e.emp_name, e.salary
--     FROM employees e
--     WHERE e.salary IS NOT NULL
--     ORDER BY e.salary
-- )
-- WHERE ROWNUM <= 4;

-- 4
-- SELECT *
-- FROM (
--     SELECT e.emp_name, e.hire_date
--     FROM employees e
--     ORDER BY e.hire_date DESC
-- )
-- WHERE ROWNUM <= 3;

-- 5
-- SELECT *
-- FROM (
--     SELECT d.dept_id, d.dept_name
--     FROM departments d
--     ORDER BY d.dept_name
-- )
-- WHERE ROWNUM <= 2;

-- 6
-- SELECT *
-- FROM (
--     SELECT e.emp_name,
--            e.salary,
--            ROW_NUMBER() OVER (ORDER BY e.salary DESC NULLS LAST) AS rn
--     FROM employees e
-- )
-- ORDER BY rn;


-- 7
-- SELECT *
-- FROM (
--     SELECT d.dept_name,
--            e.emp_name,
--            e.salary,
--            ROW_NUMBER() OVER (
--                PARTITION BY e.dept_id
--                ORDER BY e.salary DESC NULLS LAST
--            ) AS rn
--     FROM employees e
--     LEFT JOIN departments d
--         ON e.dept_id = d.dept_id
-- )
-- ORDER BY dept_name, rn;

-- 8
-- SELECT *
-- FROM (
--     SELECT d.dept_name,
--            e.emp_name,
--            e.salary,
--            ROW_NUMBER() OVER (
--                PARTITION BY e.dept_id
--                ORDER BY e.salary DESC NULLS LAST
--            ) AS rn
--     FROM employees e
--     LEFT JOIN departments d
--         ON e.dept_id = d.dept_id
-- )
-- WHERE rn = 1;

-- 9
-- SELECT *
-- FROM (
--     SELECT e.emp_name,
--            e.salary,
--            ROW_NUMBER() OVER (ORDER BY e.salary DESC NULLS LAST) AS rn
--     FROM employees e
-- )
-- WHERE rn = 2;

-- 10
-- SELECT *
-- FROM (
--     SELECT e.emp_name,
--            e.hire_date,
--            ROW_NUMBER() OVER (ORDER BY e.hire_date) AS rn
--     FROM employees e
-- )
-- WHERE rn BETWEEN 3 AND 5;

-- 11
-- SELECT *
-- FROM (
--     SELECT e.emp_name,
--            e.salary,
--            RANK() OVER (ORDER BY e.salary DESC NULLS LAST) AS sal_rank
--     FROM employees e
-- )
-- ORDER BY sal_rank;

-- 12
-- SELECT *
-- FROM (
--     SELECT d.dept_name,
--            e.emp_name,
--            e.salary,
--            RANK() OVER (
--                PARTITION BY e.dept_id
--                ORDER BY e.salary DESC NULLS LAST
--            ) AS dept_rank
--     FROM employees e
--     LEFT JOIN departments d
--         ON e.dept_id = d.dept_id
-- )
-- ORDER BY dept_name, dept_rank;

-- 13
-- SELECT *
-- FROM (
--     SELECT e.emp_name,
--            e.salary,
--            RANK() OVER (ORDER BY e.salary DESC NULLS LAST) AS sal_rank
--     FROM employees e
-- )
-- WHERE sal_rank = 1;

-- 14
-- SELECT *
-- FROM (
--     SELECT d.dept_name,
--            e.emp_name,
--            e.salary,
--            RANK() OVER (
--                PARTITION BY e.dept_id
--                ORDER BY e.salary DESC NULLS LAST
--            ) AS dept_rank
--     FROM employees e
--     LEFT JOIN departments d
--         ON e.dept_id = d.dept_id
-- )
-- WHERE dept_rank <= 2
-- ORDER BY dept_name, dept_rank;

-- 15
-- SELECT *
-- FROM (
--     SELECT e.emp_name,
--            e.hire_date,
--            RANK() OVER (ORDER BY e.hire_date) AS hire_rank
--     FROM employees e
-- )
-- ORDER BY hire_rank;


-- 16
-- SELECT *
-- FROM (
--     SELECT e.emp_name,
--            e.salary,
--            DENSE_RANK() OVER (ORDER BY e.salary DESC NULLS LAST) AS dense_sal_rank
--     FROM employees e
-- )
-- ORDER BY dense_sal_rank;


-- 17
-- SELECT *
-- FROM (
--     SELECT d.dept_name,
--            e.emp_name,
--            e.salary,
--            DENSE_RANK() OVER (
--                PARTITION BY e.dept_id
--                ORDER BY e.salary DESC NULLS LAST
--            ) AS dense_dept_rank
--     FROM employees e
--     LEFT JOIN departments d
--         ON e.dept_id = d.dept_id
-- )
-- ORDER BY dept_name, dense_dept_rank;

-- 18
-- SELECT *
-- FROM (
--     SELECT e.emp_name,
--            e.salary,
--            DENSE_RANK() OVER (ORDER BY e.salary DESC NULLS LAST) AS dense_sal_rank
--     FROM employees e
-- )
-- WHERE dense_sal_rank = 2;

-- 19
-- SELECT *
-- FROM (
--     SELECT d.dept_name,
--            e.emp_name,
--            e.salary,
--            DENSE_RANK() OVER (
--                PARTITION BY e.dept_id
--                ORDER BY e.salary DESC NULLS LAST
--            ) AS dense_dept_rank
--     FROM employees e
--     LEFT JOIN departments d
--         ON e.dept_id = d.dept_id
-- )
-- WHERE dense_dept_rank <= 2
-- ORDER BY dept_name, dense_dept_rank;

-- 20
-- SELECT *
-- FROM (
--     SELECT e.emp_name,
--            e.hire_date,
--            DENSE_RANK() OVER (ORDER BY e.hire_date DESC) AS dense_hire_rank
--     FROM employees e
-- )
-- ORDER BY dense_hire_rank;

-- 21
-- SELECT *
-- FROM (
--     SELECT e.emp_name,
--            e.salary,
--            LEAD(e.salary) OVER (ORDER BY e.salary DESC NULLS LAST) AS next_salary
--     FROM employees e
-- )
-- ORDER BY salary DESC NULLS LAST;

-- 22
-- SELECT *
-- FROM (
--     SELECT d.dept_name,
--            e.emp_name,
--            e.hire_date,
--            LEAD(e.hire_date) OVER (
--                PARTITION BY e.dept_id
--                ORDER BY e.hire_date
--            ) AS next_hire_date
--     FROM employees e
--     LEFT JOIN departments d
--         ON e.dept_id = d.dept_id
-- )
-- ORDER BY dept_name, hire_date;

-- 23
-- SELECT *
-- FROM (
--     SELECT e.emp_name,
--            e.salary,
--            LEAD(e.salary) OVER (ORDER BY e.salary DESC NULLS LAST) AS next_salary,
--            e.salary - LEAD(e.salary) OVER (ORDER BY e.salary DESC NULLS LAST) AS salary_gap
--     FROM employees e
--     WHERE e.salary IS NOT NULL
-- )
-- ORDER BY salary DESC;

-- 24
-- SELECT *
-- FROM (
--     SELECT e.emp_id,
--            e.emp_name,
--            LEAD(e.emp_name) OVER (ORDER BY e.emp_id) AS next_emp_name
--     FROM employees e
-- )
-- ORDER BY emp_id;

-- 25
-- SELECT *
-- FROM (
--     SELECT e.emp_name,
--            e.salary,
--            LEAD(e.salary) OVER (ORDER BY e.salary DESC NULLS LAST) AS next_salary
--     FROM employees e
--     WHERE e.salary IS NOT NULL
-- )
-- WHERE next_salary IS NULL;

-- 26
-- SELECT *
-- FROM (
--     SELECT e.emp_name,
--            e.salary,
--            LAG(e.salary) OVER (ORDER BY e.salary DESC NULLS LAST) AS prev_salary
--     FROM employees e
-- )
-- ORDER BY salary DESC NULLS LAST;

-- 27
-- SELECT *
-- FROM (
--     SELECT d.dept_name,
--            e.emp_name,
--            e.hire_date,
--            LAG(e.hire_date) OVER (
--                PARTITION BY e.dept_id
--                ORDER BY e.hire_date
--            ) AS prev_hire_date
--     FROM employees e
--     LEFT JOIN departments d
--         ON e.dept_id = d.dept_id
-- )
-- ORDER BY dept_name, hire_date;

-- 28
-- SELECT *
-- FROM (
--     SELECT e.emp_name,
--            e.salary,
--            LAG(e.salary) OVER (ORDER BY e.salary DESC NULLS LAST) AS prev_salary,
--            e.salary - LAG(e.salary) OVER (ORDER BY e.salary DESC NULLS LAST) AS diff_prev
--     FROM employees e
--     WHERE e.salary IS NOT NULL
-- )
-- ORDER BY salary DESC;

-- 29
-- SELECT *
-- FROM (
--     SELECT e.emp_id,
--            e.emp_name,
--            LAG(e.emp_name) OVER (ORDER BY e.emp_id) AS prev_emp_name
--     FROM employees e
-- )
-- ORDER BY emp_id;

-- SELECT *
-- FROM (
--     SELECT e.emp_name,
--            e.salary,
--            LAG(e.salary) OVER (ORDER BY e.salary DESC NULLS LAST) AS prev_salary
--     FROM employees e
--     WHERE e.salary IS NOT NULL
-- )
-- WHERE prev_salary IS NULL;